### ISSUE TITLE
Link to legacy project links to self?

### ISSUE THREAD

**Issue by MarcelRobitaille** [zapta/simple_stepper_motor_analyzer#1]
The readme of this repo has a link to the "old" design, but it's a link to the repo itself. I think you mean to link to the legacy repo: https://github.com/zapta/legacy_stepper_motor_analyzer

**Comment by zapta** [comment]
Thanks for letting me know. Fixed.

**Comment by zapta** [comment]
Thanks. I replaced the broken BOM link with a link to the JLCPCB production files (gerbers and files for their SMD assembly service). The Pico, current sensors, and stepper motor connectors are not included since I solder them manually.  

I hope to fine time to write more details assembly instructions, e.g. cutting the stepper motor connector pins to the right length using the 3D printed jig.

Regardless, building this design is easier than the previous one IMO.

**Comment by MarcelRobitaille** [comment]
I already bought the old one. That's why I was looking for the legacy link. Thought I'd point out the BOM too. Thanks for making this. It's an awesome project.

**Comment by zapta** [comment]
The old and the new designs have exactly the same capabilities so
should work for you. Make sure to pull up the RD pin of the TFT header
to +3.3v. That is missing from the PCB design and is covered by a note I
added later.

**Comment by zapta** [comment]
Added BOM file.
